# Generated by .github/workflows/app-release.yml in stan-ely/qrdrop.
# Hand edits here are overwritten on the next release; change the
# template in that workflow instead.
cask "qrdrop-app" do
  version "1.0.0"
  sha256 "dbd3a4125db0479fe23ff49e9062adba7ed4198e36213eb709de36468853fc77"

  url "https://github.com/stan-ely/qrdrop/releases/download/app-v1.0.0/qrdrop_1.0.0_aarch64.dmg",
      verified: "github.com/stan-ely/qrdrop/"
  name "qrdrop"
  desc "Send a file straight from one device to another, end-to-end encrypted"
  homepage "https://github.com/stan-ely/qrdrop"

  # The desktop job builds one dmg, on an Apple-silicon runner.
  depends_on arch: :arm64
  depends_on macos: ">= :big_sur"

  app "qrdrop.app"

  zap trash: [
    "~/Library/Saved Application State/com.stan-ely.qrdrop.savedState",
    "~/Library/WebKit/com.stan-ely.qrdrop",
  ]

  caveats <<~EOS
    qrdrop is not code-signed. There is no Apple Developer account behind
    this project, so macOS will refuse to open it the first time and say
    it cannot check the app for malicious software.

    If you decide to trust it:

      xattr -d com.apple.quarantine /Applications/qrdrop.app

    That warning is accurate -- nobody has vouched for this binary. The
    dmg does carry a build provenance attestation, which is a verifiable
    claim about where it was built and not a signature:

      gh attestation verify <file> --repo stan-ely/qrdrop
  EOS
end
