# Generated by .github/workflows/publish.yml in stan-ely/qrdrop.
# Hand edits here are overwritten on the next release; change the
# template in that workflow instead.
class Qrdrop < Formula
  desc "Send a file straight from one device to another, end-to-end encrypted"
  homepage "https://github.com/stan-ely/qrdrop"
  url "https://registry.npmjs.org/qrdrop/-/qrdrop-0.5.0.tgz"
  sha256 "4a8dc46cb21a826ebcea7d3fd36757db05c448bd1022585c1504d2fa50fe83bc"
  license "MIT"

  # Rather than vendoring a runtime: brew's node is well past the
  # engines floor of 22, and a bundled Node is ~58 MB against a
  # published tarball of about 660 kB.
  depends_on "node"

  def install
    # std_npm_args passes --ignore-scripts, which is safe here for a
    # specific reason worth writing down: node-datachannel ships its
    # native binary as eight per-platform npm packages that npm picks
    # between using os/cpu, not as a postinstall that downloads one.
    # If it ever goes back to prebuild-install, this formula breaks
    # into a CLI that pairs and then cannot open a peer connection --
    # the failure src/node/rtc.js writes its long error message for.
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/qrdrop --version")
  end
end
